# Generated by Django 4.2.1 on 2023-05-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_inf_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_of_reviews',
            field=models.IntegerField(default=111, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='inf_about',
            field=models.TextField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='core.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
